### ISSUE TITLE
No longer works on 11.1

### ISSUE THREAD

**Issue by AquaBat** [yellows8/stickerhax#5]
Once the save file with the hax is selected, it goes through the process, but once it says "The homemenu ropbin is ready", the game crashes back to the normal home menu. Apparently it can't load the Homebrew main menu properly.

**Comment by yellows8** [comment]
Reinstall for v11.1 via other hax.

**Comment by masonraus** [comment]
This is referring to 11.1.0-35 correct? I just encountered this problem today...

**Comment by yellows8** [comment]
Yes.
